### ISSUE TITLE
iam module apply to existent structure

### ISSUE THREAD

**Issue by alyabievgy** [yandex-cloud/yc-architect-solution-library#6]
При попытке изменить роли существующего сервисного аккаунта получил резонную ошибку, что его имя уже занято.
Но импортировать его в стейт файл не вышло:
```
terraform import yandex_iam_service_account.sa["sa"] <id>
For information on valid syntax, see:
https://www.terraform.io/docs/cli/state/resource-addressing.html
╷
│ Error: Index value required
│ 
│   on <import-address> line 1:
│    1: yandex_iam_service_account.sa[sa]
│ 
│ Index brackets must contain either a literal number or a literal string.
```
хотя именно с такими индексами они там и хранятся:
```
{
      "mode": "managed",
      "type": "yandex_iam_service_account",
      "name": "sa",
      "provider": "provider[\"registry.terraform.io/yandex-cloud/yandex\"]",
      "instances": [
        {
          "index_key": "sa",
          "schema_version": 0,
          "attributes": {
            "created_at": "2021-08-05T14:23:04Z",
```

```
Terraform v1.0.3 on linux_amd64
+ provider registry.terraform.io/yandex-cloud/yandex v0.61.0

```

**Comment by romati88** [comment]
Для поиска корректного пути ресурса можно посмотреть 
`terraform state list`
Корректная команда для импорта, где 'iam' - имя модуля, a 'sa-name' - имя SA соответственно:
`terraform import 'module.iam.yandex_iam_service_account.sa["sa-name"]' aje0am0b06tj6v8mrXXX`
после добавить sa-name в значение var.sa_role_mapping и выполнить terraform plan для проверки.

Как в принципе для управления правами существующих заранее SA можно использовать var.folder_user_role_mapping, где users = ["serviceAccount:aje0k467i3bs3XXXXX", ].

**Comment by alyabievgy** [comment]
Спасибо за ликбез, `'module.iam.yandex_iam_service_account.sa["sa-name"]'` работает как надо!
